name: Build Linux Image Template
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
        description: "Name of main tag and workflow file."
      tags:
        type: string
        required: false
        description: "Extra tags to use besides main tag."
      files:
        type: string
        required: false
        description: "Extra files to watch for change"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Check changed Dockerfile
        id: changed-dockerfile
        uses: tj-actions/changed-files@v41
        with:
          files: dockerfiles/${{ inputs.name }}/Dockerfile

      - name: Docker Login
        if: steps.changed-dockerfile.outputs.any_changed == 'true'
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Image
        if: steps.changed-dockerfile.outputs.any_changed == 'true'
        run: docker build -t mrnavastar/conductor:${{ inputs.name }} .
        working-directory: dockerfiles/${{ inputs.name }}

      # master
      - name: Tag Image
        if: ${{ (steps.changed-dockerfile.outputs.any_changed == 'true') && (github.ref == 'refs/heads/master') && (inputs.tags != '') }}
        run: >
          for TAG in ${{ inputs.tags }};
          do
            docker tag mrnavastar/conductor:${{ inputs.name }} mrnavastar/conductor:${TAG};
          done

      - name: Push Image
        if: ${{ (steps.changed-dockerfile.outputs.any_changed == 'true') && (github.ref == 'refs/heads/master') }}
        run: docker push mrnavastar/conductor --all-tags