on:
  push:
    branches:
      - 'master'

jobs:
  server:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
    with:
      name: server

  server-java:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
    needs: server
    with:
      name: server-java